import { styled } from "@mui/material";
export const CostumeButtonStyled = styled("div")(() => ({
  // 1
  "& .primaryBtn": {
    background: "linear-gradient(102.45deg, #0000FF 0%, #BB33FF 100%)",
    color: "#FFFFFF",
    border: "1px solid #BB33FF",
    borderRadius: "12px",
    height: "48px",
    width: "100%",
    fontSize: "16px",
    textTransform: "capitalize",
    boxShadow: "0px 10px 30px -10px #0000FF4D",
    fontWeight: "700",
    transition: "all 0.4s ease",
  },
  "& .primaryBtn:hover": {
    background: "linear-gradient(102.45deg, #0000FF 0%, #BB33FF 100%)",
    color: "#FFFFFF",
    border: "1px solid #BB33FF",
    transition: "all 0.4s ease",
    boxShadow: "0px 10px 30px -10px #0000FF4D",
  },

  "& .successBtn": {
    background: "#16A2491A",
    color: "#16A249",
    fontSize: "12px",
    borderRadius: "20px",
    padding: "2px 10px",
    border: "1px solid #16A24933",
    height: "21px",
    width: "100%",
    textTransform: "capitalize",
    boxShadow: "none",
    fontWeight: "400",
    transition: "all 0.4s ease",
  },
  "& .successBtn:hover": {
    boxShadow: "none",
    color: "#16A249",
    border: "1px solid #16A249",
    transition: "all 0.4s ease",
  },

  "& .customstepperBtn": {
    background: "#0C1518",
    color: "#FFFFFF",
    border: "1px solid #0C1518",
    borderRadius: "6px",
    height: "46px",
    width: "100%",
    fontSize: "16px",
    textTransform: "capitalize",
    boxShadow: "none",
    fontWeight: "700",
    transition: "all 0.4s ease",
  },
  "& .customstepperBtn:hover": {
    background: "transparent !important",
    color: "#0C1518",
    border: "1px solid #0C1518",
    transition: "all 0.4s ease",
    boxShadow: "none",
  },

  "& .outlineBtn": {
    background: "#FFFFFF",
    color: "#0A0A0A",
    border: "1px solid #E2E8F0",
    borderRadius: "10px",
    height: "40px",
    width: "100%",
    fontSize: "14px",
    textTransform: "capitalize",
    boxShadow: "none",
    fontWeight: "600",
    transition: "all 0.4s ease",
  },
  "& .outlineBtn:hover": {
    background: "transparent !important",
    color: "#0C1518",
    border: "1px solid #0C1518",
    transition: "all 0.5s ease",
    boxShadow: "none",
  },

  "& .lavenderBtn": {
    background: "#9B59B612",
    color: "#9B59B6",
    border: "1px solid #9B59B6",
    borderRadius: "8px",
    height: "46px",
    width: "100%",
    fontSize: "14px",
    textTransform: "capitalize",
    boxShadow: "none",
    fontWeight: "600",
    transition: "all 0.4s ease",
  },
  "& .lavenderBtn:hover": {
    background: "transparent !important",
    color: "#9B59B6",
    border: "1px solid #9B59B6",
    transition: "all 0.5s ease",
    boxShadow: "none",
  },

  // DISABLED STYLE BTN
  "& .inheritCssComonBtn, .inheritCssComonBtn:hover": {
    background: "transparent",
    color: "#0F172A",
    border: "none",
    fontSize: "16px",
    textTransform: "capitalize",
    boxShadow: "none",
    padding: "0",
    lineHeight: "inherit",
    width: "unset",
    minWidth: "fit-content",
    borderRadius: "6px",
  },
}));
